baseurl = "https://terraphilosofica.github.io/hugo-darkdoc-theme/"
title = "Photo portfolio"
theme = "hugo-darkdoc-theme"
metadataformat = "yaml"
pygmentsUseClasses = true

[params]
	# General information
	author = "Aleksandra Veljkovic"
	description = "I am philosopher interested in webdesign and photography"
	copyright = "Released under my prefered license"

  #demo website
  demo_site = "http://demo.example.com"

	# Repository
	provider = "GitHub"
	repo_url = "https://terraphilosofica.github.io/hugo-darkdoc-theme/"
	repo_id = "hugo-darkdoc-theme"

	version = "1.0.0"
	favicon = ""

	permalink = "#"

[social]
	github  = "terraphilosofica"

[[menu.main]]
	name   = "Home"
	url    = "home/"
	weight = 0

[[menu.main]]
	name   = "About "
	url    = "about/"
  weight = 10

