name = "Darkdoc"

homepage = "https://terraphilosofica.github.io/hugo-darkdoc-theme/"
tags = ["bootstrap", "documentation", "responsive"]
features = ["", ""]
min_version = 0.14

[author]
  name = "Aleksandra Veljkovic"
  homepage = "https://terraphilosofica.github.io/"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
